package vc.com.software.gerenciadordeprocessos;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renan Gomes Barreto
 */
public class IFProcesso extends javax.swing.JInternalFrame {

    Processo p = new Processo();
    boolean editando = false;

    /**
     * Creates new form IFLeilao
     */
    public IFProcesso() {
        p = new Processo();
        initComponents();
        atualizar();
    }

    public IFProcesso(Processo p) {
        if (p != null) {
            this.p = p;
        }
        initComponents();
        atualizar();
        editando = true;
        fcaixa.setEnabled(false);
        fsequencia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fcpf_cnpj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fobservacoes = new javax.swing.JTextArea(){

            @Override
            public void setEditable(boolean b){
                super.setEditable(b);
                setOpaque(b);
            }

        };
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fcaixa = new javax.swing.JTextField();
        fsequencia = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        fplaca = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Processo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/vc/com/software/gerenciadordeprocessos/img/pen-b-16.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 400));
        setVisible(true);

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vc/com/software/gerenciadordeprocessos/img/delete24.png"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Placa:");

        jLabel3.setText("CPF/CNPJ:");

        jLabel10.setText("Observações:");

        jScrollPane1.setEnabled(false);

        fobservacoes.setColumns(20);
        fobservacoes.setRows(2);
        jScrollPane1.setViewportView(fobservacoes);

        jLabel11.setText("Caixa:");

        jLabel12.setText("Sequencia:");

        fcaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fcaixaKeyReleased(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vc/com/software/gerenciadordeprocessos/img/save24.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fcaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fsequencia, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addComponent(fcpf_cnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fnome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fplaca)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(fsequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fcpf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar)
                    .addComponent(btSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
    this.dispose();
}//GEN-LAST:event_btFecharActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void fcaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcaixaKeyReleased
        if (!fcaixa.getText().trim().toUpperCase().equals("")) {

            ArrayList<Processo> somentenacaixa = new ArrayList<>();
            for (Processo proc2 : Principal.processos) {
                if (proc2.getCaixa().toUpperCase().trim().equals(fcaixa.getText().trim().toUpperCase())) {
                    somentenacaixa.add(proc2);
                }
            }
            boolean vazio = true;
            for (int i = 1; i <= 300; i++) {
                vazio = true;
                for (Processo proc : somentenacaixa) {
                    if (proc.getSequencia().toUpperCase().trim().equals(Integer.toString(i))) {
                        vazio = false;
                        break;
                    }
                }
                if (vazio) {
                    fsequencia.setText(Integer.toString(i));
                    break;
                }
            }
            if (!vazio) {
                JOptionPane.showMessageDialog(null, "A caixa está cheia. Por favor, crie outra caixa.");
            }
        }
    }//GEN-LAST:event_fcaixaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField fcaixa;
    private javax.swing.JTextField fcpf_cnpj;
    private javax.swing.JTextField fnome;
    private javax.swing.JTextArea fobservacoes;
    private javax.swing.JTextField fplaca;
    private javax.swing.JTextField fsequencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void atualizar() {
        String nome = p.getNome().trim();
        fnome.setText(nome);
        fplaca.setText(p.getPlaca().trim().toUpperCase());
        fcaixa.setText(p.getCaixa().trim());
        fsequencia.setText(p.getSequencia().trim());
        fcpf_cnpj.setText(p.getCpf_cnpj().trim());
        fobservacoes.setText(p.getObservacoes().trim());
    }

    private synchronized void salvar() {
        if (fnome.getText().toUpperCase().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o nome completo do cliente.");
            return;
        }
        if (fplaca.getText().toUpperCase().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a Placa.");
            return;
        }
        if (fcaixa.getText().toUpperCase().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o código da caixa.");
            return;
        }
        if (fcaixa.getText().toUpperCase().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o código da caixa.");
            return;
        }
        
        p.setNome(fnome.getText());
        p.setPlaca(fplaca.getText().toUpperCase().trim());
        p.setCaixa(fcaixa.getText().toUpperCase().trim());
        p.setSequencia(fsequencia.getText().toUpperCase().trim());
        p.setCpf_cnpj(fcpf_cnpj.getText().toUpperCase().trim());
        p.setObservacoes(fobservacoes.getText());
        
        
        
        try {
            Principal.janelaPrincipal.salvarProcesso(p);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(IFProcesso.class.getName()).log(Level.SEVERE, "Os dados não foram salvos", ex);
            JOptionPane.showMessageDialog(this, "Os dados não foram salvos.", "Erro na gravação dos dados", JOptionPane.ERROR_MESSAGE);
        }
    }
}
